#!/usr/bin/env python3
"""Assemble reports/top-picks/YYYY-MM-DD.md from per-market bodies + status."""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
from pathlib import Path


def read_text(path: Path) -> str:
    if not path.exists():
        return "(tidak ada output)"
    text = path.read_text(encoding="utf-8").strip()
    return text or "(kosong)"


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--today", required=True)
    p.add_argument("--strictness", default="balanced")
    p.add_argument("--limit", type=int, default=5)
    p.add_argument("--min-pct", default="15")
    p.add_argument("--min-q-stock", default="Bagus")
    p.add_argument("--min-q-crypto", default="Best")
    p.add_argument("--crypto-gate", default="--safe-only --ta-confirm --macro-filter")
    p.add_argument("--st-idx", default="skip")
    p.add_argument("--st-us", default="skip")
    p.add_argument("--st-crypto", default="skip")
    p.add_argument("--body-idx", type=Path, required=True)
    p.add_argument("--body-us", type=Path, required=True)
    p.add_argument("--body-crypto", type=Path, required=True)
    p.add_argument("--out-dir", type=Path, default=Path("reports/top-picks"))
    args = p.parse_args()

    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    body_idx = read_text(args.body_idx)
    body_us = read_text(args.body_us)
    body_crypto = read_text(args.body_crypto)

    md = f"""# Top Picks Today
**Tanggal:** {args.today}  |  **UTC:** {stamp}  |  **Strictness:** {args.strictness}  |  **Limit/pasar:** {args.limit}

> Screener + QC otomatis. **Bukan saran investasi.** Paper/heuristik saja.

---

## Ringkasan entry

| Pasar | Status | Gate |
|-------|--------|------|
| IDX | {args.st_idx} | UV≥{args.min_pct}% · kualitas≥{args.min_q_stock} · QC (Yahoo) |
| US | {args.st_us} | UV≥{args.min_pct}% · kualitas≥{args.min_q_stock} |
| Crypto | {args.st_crypto} | UV≥{args.min_pct}% · kualitas≥{args.min_q_crypto} · {args.crypto_gate} |

**Prioritas modal:** IDX (core) → US (defensif) → Crypto (sizing kecil)

### Matriks cepat

| Kondisi | Aksi |
|---------|------|
| Lolos filter + QC/TA OK | **Entry kandidat** |
| UV tinggi tapi QC/TA gagal / caveat | **Tunggu / Skip** |
| 0 lolos di semua pasar | **Cash** — jangan dipaksa beli |

---

## IDX — boleh entry (QC)

~~~
{body_idx}
~~~

---

## US — boleh entry

~~~
{body_us}
~~~

---

## Crypto — boleh entry (safe)

~~~
{body_crypto}
~~~

---

## Skip list hari ini

- Caveat forward EPS agresif (US growth menyamar value)
- IDX PBV ekstrem / PER one-off earning
- Crypto unlock risk Tinggi / value trap / alt di BTC season ekstrem
- UV ekstrem tanpa konfirmasi kualitas + QC/TA

_Generated by `run_top_picks.sh` · reports/top-picks/{args.today}.md_
"""

    args.out_dir.mkdir(parents=True, exist_ok=True)
    out = args.out_dir / f"{args.today}.md"
    latest = args.out_dir / "latest.md"
    out.write_text(md, encoding="utf-8")
    latest.write_text(md, encoding="utf-8")
    print(f"Wrote {out}")
    print(f"Wrote {latest}")


if __name__ == "__main__":
    main()
